version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    timezone: Asia/Tokyo
  open-pull-requests-limit: 99
  reviewers:
  - nwtgck
  assignees:
  - nwtgck
  ignore:
  - dependency-name: vue-cli-plugin-vuetify
    versions:
    - 2.1.0
    - 2.1.1
    - 2.2.0
    - 2.2.1
    - 2.2.2
    - 2.3.0
    - 2.3.1
  - dependency-name: "@vue/cli-service"
    versions:
    - 4.5.11
    - 4.5.12
  - dependency-name: "@vue/cli-plugin-typescript"
    versions:
    - 4.5.11
    - 4.5.12
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.10.1
    - 3.10.2
    - 3.11.0
    - 3.8.3
    - 3.9.0
    - 3.9.1
  - dependency-name: "@vue/cli-plugin-babel"
    versions:
    - 4.5.11
    - 4.5.12
  - dependency-name: "@vue/cli-plugin-pwa"
    versions:
    - 4.5.11
    - 4.5.12
  - dependency-name: sass
    versions:
    - 1.32.11
    - 1.32.5
    - 1.32.6
    - 1.32.7
    - 1.32.8
  - dependency-name: vuetify
    versions:
    - 2.4.10
    - 2.4.11
    - 2.4.3
    - 2.4.4
    - 2.4.5
    - 2.4.6
    - 2.4.7
    - 2.4.8
    - 2.4.9
  - dependency-name: vue-fullscreen
    versions:
    - 2.2.0
    - 2.3.1
    - 2.3.2
    - 2.3.3
    - 2.3.4
    - 2.3.5
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: vue-template-compiler
    versions:
    - 2.6.12
  - dependency-name: vue
    versions:
    - 2.6.12
  - dependency-name: typescript
    versions:
    - 3.9.7
    - 3.9.8
    - 3.9.9
  - dependency-name: vuetify-loader
    versions:
    - 1.7.1
    - 1.7.2
  - dependency-name: elliptic
    versions:
    - 6.5.3
    - 6.5.4
  - dependency-name: sass-loader
    versions:
    - 10.1.1
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: register-service-worker
    versions:
    - 1.7.2
  - dependency-name: highlight.js
    versions:
    - 9.18.5
  - dependency-name: vue-class-component
    versions:
    - 7.2.6
  - dependency-name: http-proxy
    versions:
    - 1.18.1
  - dependency-name: dot-prop
    versions:
    - 4.2.1
  - dependency-name: lodash
    versions:
    - 4.17.20
